import type { OwlEvent, Person } from "./types";

export const demoPeople: Person[] = [
  { id: "maya", name: "Maya Chen", initials: "MC", subtitle: "Architecture · Sophomore", college: "Jones", color: "#d97956" },
  { id: "jordan", name: "Jordan Brooks", initials: "JB", subtitle: "Computer Science · Freshman", college: "Baker", color: "#5d85c3" },
  { id: "priya", name: "Priya Shah", initials: "PS", subtitle: "Bioengineering · Junior", college: "McMurtry", color: "#9871b5" },
  { id: "eli", name: "Eli Navarro", initials: "EN", subtitle: "Economics · Sophomore", college: "Wiess", color: "#3f8d74" },
  { id: "sam", name: "Sam Lee", initials: "SL", subtitle: "Music · Freshman", college: "Duncan", color: "#b7814e" },
];

export const demoMobileEvents: OwlEvent[] = [
  {
    id: "ping-pong",
    title: "Casual ping pong",
    description: "Nothing competitive—just a few games and a chance to meet someone new. All levels welcome!",
    location: "RMC Game Room",
    startsAt: "2026-09-05T19:00:00-05:00",
    capacity: 6,
    visibility: "public",
    category: "Games",
    host: demoPeople[0],
    attendees: demoPeople.slice(0, 3),
    pending: [],
  },
  {
    id: "coffee",
    title: "Coffee + campus walk",
    description: "Grab a drink at Audrey's and wander around campus before classes get too busy.",
    location: "Audrey's Coffee House",
    startsAt: "2026-09-06T10:30:00-05:00",
    capacity: 5,
    visibility: "public",
    category: "Chill",
    host: demoPeople[3],
    attendees: [demoPeople[3], demoPeople[4]],
    pending: [],
  },
  {
    id: "sunset",
    title: "Sunset study break",
    description: "Bring a snack or a frisbee. We’ll hang out on the lawn and reset before the week starts.",
    location: "Engineering Quad",
    startsAt: "2026-09-06T18:45:00-05:00",
    capacity: 8,
    visibility: "public",
    category: "Outdoors",
    inviteCode: "demo-sunset",
    host: { id: "demo-user", name: "You", initials: "YO", subtitle: "Event host", college: "Duncan", color: "#1d4e4a" },
    attendees: [{ id: "demo-user", name: "You", initials: "YO", subtitle: "Event host", college: "Duncan", color: "#1d4e4a" }],
    pending: [demoPeople[1], demoPeople[4]],
    isOwner: true,
  },
  {
    id: "tacos",
    title: "Late-night tacos",
    description: "Small group taco run—invite only.",
    location: "Lovett Sallyport",
    startsAt: "2026-09-07T21:00:00-05:00",
    capacity: 4,
    visibility: "private",
    category: "Food",
    inviteCode: "demo-tacos",
    host: demoPeople[2],
    attendees: [demoPeople[2]],
    pending: [],
    membership: "invited",
  },
];
