import type { OwlEvent, Person } from "./types";

export const people: Person[] = [
  { id: "maya", name: "Maya Chen", initials: "MC", major: "Architecture", year: "Sophomore", college: "Jones", color: "#d97956" },
  { id: "jordan", name: "Jordan Brooks", initials: "JB", major: "Computer Science", year: "Freshman", college: "Baker", color: "#5d85c3" },
  { id: "priya", name: "Priya Shah", initials: "PS", major: "Bioengineering", year: "Junior", college: "McMurtry", color: "#9871b5" },
  { id: "eli", name: "Eli Navarro", initials: "EN", major: "Economics", year: "Sophomore", college: "Wiess", color: "#3f8d74" },
  { id: "sam", name: "Sam Lee", initials: "SL", major: "Music", year: "Freshman", college: "Duncan", color: "#b7814e" },
];

export const demoEvents: OwlEvent[] = [
  {
    id: "ping-pong",
    title: "Casual ping pong",
    description: "Nothing competitive—just a few games and a chance to meet someone new. All levels welcome!",
    location: "RMC Game Room",
    date: "2026-09-05",
    time: "7:00 PM",
    capacity: 6,
    visibility: "public",
    category: "Games",
    host: people[0],
    attendees: [people[0], people[1], people[2]],
    pending: [],
  },
  {
    id: "coffee-walk",
    title: "Coffee + campus walk",
    description: "Grab a drink at Audrey's and wander around campus before classes get too busy.",
    location: "Audrey's Coffee House",
    date: "2026-09-06",
    time: "10:30 AM",
    capacity: 5,
    visibility: "public",
    category: "Chill",
    host: people[3],
    attendees: [people[3], people[4]],
    pending: [],
  },
  {
    id: "study-break",
    title: "Sunset study break",
    description: "Bring a snack or a frisbee. We’ll hang out on the lawn and reset before the week starts.",
    location: "Engineering Quad",
    date: "2026-09-06",
    time: "6:45 PM",
    capacity: 8,
    visibility: "public",
    category: "Outdoors",
    inviteCode: "demo-study-break",
    host: { id: "you", name: "You", initials: "YO", major: "", year: "", college: "", color: "#1d4e4a" },
    attendees: [{ id: "you", name: "You", initials: "YO", major: "", year: "", college: "", color: "#1d4e4a" }],
    pending: [people[1], people[4]],
    isOwner: true,
  },
  {
    id: "tacos",
    title: "Late-night tacos",
    description: "Small group taco run—invite only.",
    location: "Meet at Lovett Sallyport",
    date: "2026-09-07",
    time: "9:00 PM",
    capacity: 4,
    visibility: "private",
    category: "Food",
    inviteCode: "demo-tacos",
    host: people[2],
    attendees: [people[2]],
    pending: [],
    membership: "invited",
  },
];
